### ISSUE TITLE
[Chore] 린트 수정, 헤더 템플릿 수정

### ISSUE THREAD

**Issue by hhajime** [DeveloperAcademy-POSTECH/MacC-Team10-OFO#11]
## 💡 Issue
- 합의된 린트 및 헤더 템플릿을 수정합니다.

## 📝 Todo
- [ ] 린트 수정
- [ ] 헤더 템플릿 수정

**Comment by sozohoy** [comment]
- 머지 해드렸습니다~

**Comment by hhajime** [comment]
후행 쉼표는 저희끼리 합의한 방식대로 이행하지 못할 것 같네요..
```
# 배열과 맵에서 후행 쉼표는 적용해야 합니다.
trailing_comma:
  severity: warning
  mandatory_comma: true
```
이대로라면 적용이 되야하는데, 적용이 제대로 안되고 있어요
